package com.kingsoft.pojo.mapper;

import com.kingsoft.pojo.BookChapter;
import com.kingsoft.pojo.BookChapterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookChapterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_chapter
     *
     * @mbggenerated
     */
    int countByExample(BookChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_chapter
     *
     * @mbggenerated
     */
    int deleteByExample(BookChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_chapter
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_chapter
     *
     * @mbggenerated
     */
    int insert(BookChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_chapter
     *
     * @mbggenerated
     */
    int insertSelective(BookChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_chapter
     *
     * @mbggenerated
     */
    List<BookChapter> selectByExample(BookChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_chapter
     *
     * @mbggenerated
     */
    BookChapter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_chapter
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BookChapter record, @Param("example") BookChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_chapter
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BookChapter record, @Param("example") BookChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_chapter
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BookChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_chapter
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BookChapter record);
}