package com.kingsoft.pojo.mapper;

import com.kingsoft.pojo.BookLabel;
import com.kingsoft.pojo.BookLabelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_label
     *
     * @mbggenerated
     */
    int countByExample(BookLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_label
     *
     * @mbggenerated
     */
    int deleteByExample(BookLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_label
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_label
     *
     * @mbggenerated
     */
    int insert(BookLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_label
     *
     * @mbggenerated
     */
    int insertSelective(BookLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_label
     *
     * @mbggenerated
     */
    List<BookLabel> selectByExample(BookLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_label
     *
     * @mbggenerated
     */
    BookLabel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_label
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BookLabel record, @Param("example") BookLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_label
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BookLabel record, @Param("example") BookLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_label
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BookLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_label
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BookLabel record);
}