package com.kingsoft.pojo.mapper;

import com.kingsoft.pojo.BookSection;
import com.kingsoft.pojo.BookSectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookSectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_section
     *
     * @mbggenerated
     */
    int countByExample(BookSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_section
     *
     * @mbggenerated
     */
    int deleteByExample(BookSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_section
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_section
     *
     * @mbggenerated
     */
    int insert(BookSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_section
     *
     * @mbggenerated
     */
    int insertSelective(BookSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_section
     *
     * @mbggenerated
     */
    List<BookSection> selectByExampleWithBLOBs(BookSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_section
     *
     * @mbggenerated
     */
    List<BookSection> selectByExample(BookSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_section
     *
     * @mbggenerated
     */
    BookSection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_section
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BookSection record, @Param("example") BookSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_section
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") BookSection record, @Param("example") BookSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_section
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BookSection record, @Param("example") BookSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_section
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BookSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_section
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(BookSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book_section
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BookSection record);
}