package com.kingsoft.pojo.mapper;

import com.kingsoft.pojo.CrawlerBookType;
import com.kingsoft.pojo.CrawlerBookTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrawlerBookTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_crawler_book_type
     *
     * @mbggenerated
     */
    int countByExample(CrawlerBookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_crawler_book_type
     *
     * @mbggenerated
     */
    int deleteByExample(CrawlerBookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_crawler_book_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_crawler_book_type
     *
     * @mbggenerated
     */
    int insert(CrawlerBookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_crawler_book_type
     *
     * @mbggenerated
     */
    int insertSelective(CrawlerBookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_crawler_book_type
     *
     * @mbggenerated
     */
    List<CrawlerBookType> selectByExample(CrawlerBookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_crawler_book_type
     *
     * @mbggenerated
     */
    CrawlerBookType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_crawler_book_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CrawlerBookType record, @Param("example") CrawlerBookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_crawler_book_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CrawlerBookType record, @Param("example") CrawlerBookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_crawler_book_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CrawlerBookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_crawler_book_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CrawlerBookType record);
}