package com.kingsoft.pojo.mapper;

import com.kingsoft.pojo.YellowCrawlerError;
import com.kingsoft.pojo.YellowCrawlerErrorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YellowCrawlerErrorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_crawler_error
     *
     * @mbggenerated
     */
    int countByExample(YellowCrawlerErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_crawler_error
     *
     * @mbggenerated
     */
    int deleteByExample(YellowCrawlerErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_crawler_error
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_crawler_error
     *
     * @mbggenerated
     */
    int insert(YellowCrawlerError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_crawler_error
     *
     * @mbggenerated
     */
    int insertSelective(YellowCrawlerError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_crawler_error
     *
     * @mbggenerated
     */
    List<YellowCrawlerError> selectByExample(YellowCrawlerErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_crawler_error
     *
     * @mbggenerated
     */
    YellowCrawlerError selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_crawler_error
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YellowCrawlerError record, @Param("example") YellowCrawlerErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_crawler_error
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YellowCrawlerError record, @Param("example") YellowCrawlerErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_crawler_error
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YellowCrawlerError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_crawler_error
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YellowCrawlerError record);
}