package com.kingsoft.pojo.mapper;

import com.kingsoft.pojo.YellowBookSection;
import com.kingsoft.pojo.YellowBookSectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YellowBookSectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_book_section
     *
     * @mbggenerated
     */
    int countByExample(YellowBookSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_book_section
     *
     * @mbggenerated
     */
    int deleteByExample(YellowBookSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_book_section
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_book_section
     *
     * @mbggenerated
     */
    int insert(YellowBookSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_book_section
     *
     * @mbggenerated
     */
    int insertSelective(YellowBookSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_book_section
     *
     * @mbggenerated
     */
    List<YellowBookSection> selectByExampleWithBLOBs(YellowBookSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_book_section
     *
     * @mbggenerated
     */
    List<YellowBookSection> selectByExample(YellowBookSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_book_section
     *
     * @mbggenerated
     */
    YellowBookSection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_book_section
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YellowBookSection record, @Param("example") YellowBookSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_book_section
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") YellowBookSection record, @Param("example") YellowBookSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_book_section
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YellowBookSection record, @Param("example") YellowBookSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_book_section
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YellowBookSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_book_section
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(YellowBookSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yellow_book_section
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YellowBookSection record);
}