package com.kingsoft.pojo;

import java.util.Date;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.sub_title
     *
     * @mbggenerated
     */
    private String subTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.author_name
     *
     * @mbggenerated
     */
    private String authorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.label
     *
     * @mbggenerated
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.words
     *
     * @mbggenerated
     */
    private Integer words;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.update_state
     *
     * @mbggenerated
     */
    private Integer updateState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.channel
     *
     * @mbggenerated
     */
    private Integer channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.read_count
     *
     * @mbggenerated
     */
    private Integer readCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.on_time
     *
     * @mbggenerated
     */
    private Date onTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.off_time
     *
     * @mbggenerated
     */
    private Date offTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.vip_price
     *
     * @mbggenerated
     */
    private Integer vipPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.sale_price
     *
     * @mbggenerated
     */
    private Integer salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.publisher
     *
     * @mbggenerated
     */
    private String publisher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.publish_date
     *
     * @mbggenerated
     */
    private String publishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.cover
     *
     * @mbggenerated
     */
    private String cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.series_id
     *
     * @mbggenerated
     */
    private Integer seriesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.exchange_type
     *
     * @mbggenerated
     */
    private String exchangeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.limit_price
     *
     * @mbggenerated
     */
    private Integer limitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.limit_start_time
     *
     * @mbggenerated
     */
    private Integer limitStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.limit_end_time
     *
     * @mbggenerated
     */
    private Integer limitEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.id
     *
     * @return the value of tb_book.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.id
     *
     * @param id the value for tb_book.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.title
     *
     * @return the value of tb_book.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.title
     *
     * @param title the value for tb_book.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.sub_title
     *
     * @return the value of tb_book.sub_title
     *
     * @mbggenerated
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.sub_title
     *
     * @param subTitle the value for tb_book.sub_title
     *
     * @mbggenerated
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle == null ? null : subTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.author_name
     *
     * @return the value of tb_book.author_name
     *
     * @mbggenerated
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.author_name
     *
     * @param authorName the value for tb_book.author_name
     *
     * @mbggenerated
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName == null ? null : authorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.label
     *
     * @return the value of tb_book.label
     *
     * @mbggenerated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.label
     *
     * @param label the value for tb_book.label
     *
     * @mbggenerated
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.description
     *
     * @return the value of tb_book.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.description
     *
     * @param description the value for tb_book.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.words
     *
     * @return the value of tb_book.words
     *
     * @mbggenerated
     */
    public Integer getWords() {
        return words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.words
     *
     * @param words the value for tb_book.words
     *
     * @mbggenerated
     */
    public void setWords(Integer words) {
        this.words = words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.update_state
     *
     * @return the value of tb_book.update_state
     *
     * @mbggenerated
     */
    public Integer getUpdateState() {
        return updateState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.update_state
     *
     * @param updateState the value for tb_book.update_state
     *
     * @mbggenerated
     */
    public void setUpdateState(Integer updateState) {
        this.updateState = updateState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.channel
     *
     * @return the value of tb_book.channel
     *
     * @mbggenerated
     */
    public Integer getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.channel
     *
     * @param channel the value for tb_book.channel
     *
     * @mbggenerated
     */
    public void setChannel(Integer channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.read_count
     *
     * @return the value of tb_book.read_count
     *
     * @mbggenerated
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.read_count
     *
     * @param readCount the value for tb_book.read_count
     *
     * @mbggenerated
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.on_time
     *
     * @return the value of tb_book.on_time
     *
     * @mbggenerated
     */
    public Date getOnTime() {
        return onTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.on_time
     *
     * @param onTime the value for tb_book.on_time
     *
     * @mbggenerated
     */
    public void setOnTime(Date onTime) {
        this.onTime = onTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.off_time
     *
     * @return the value of tb_book.off_time
     *
     * @mbggenerated
     */
    public Date getOffTime() {
        return offTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.off_time
     *
     * @param offTime the value for tb_book.off_time
     *
     * @mbggenerated
     */
    public void setOffTime(Date offTime) {
        this.offTime = offTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.state
     *
     * @return the value of tb_book.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.state
     *
     * @param state the value for tb_book.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.price
     *
     * @return the value of tb_book.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.price
     *
     * @param price the value for tb_book.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.vip_price
     *
     * @return the value of tb_book.vip_price
     *
     * @mbggenerated
     */
    public Integer getVipPrice() {
        return vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.vip_price
     *
     * @param vipPrice the value for tb_book.vip_price
     *
     * @mbggenerated
     */
    public void setVipPrice(Integer vipPrice) {
        this.vipPrice = vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.sale_price
     *
     * @return the value of tb_book.sale_price
     *
     * @mbggenerated
     */
    public Integer getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.sale_price
     *
     * @param salePrice the value for tb_book.sale_price
     *
     * @mbggenerated
     */
    public void setSalePrice(Integer salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.publisher
     *
     * @return the value of tb_book.publisher
     *
     * @mbggenerated
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.publisher
     *
     * @param publisher the value for tb_book.publisher
     *
     * @mbggenerated
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.publish_date
     *
     * @return the value of tb_book.publish_date
     *
     * @mbggenerated
     */
    public String getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.publish_date
     *
     * @param publishDate the value for tb_book.publish_date
     *
     * @mbggenerated
     */
    public void setPublishDate(String publishDate) {
        this.publishDate = publishDate == null ? null : publishDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.type
     *
     * @return the value of tb_book.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.type
     *
     * @param type the value for tb_book.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.cover
     *
     * @return the value of tb_book.cover
     *
     * @mbggenerated
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.cover
     *
     * @param cover the value for tb_book.cover
     *
     * @mbggenerated
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.series_id
     *
     * @return the value of tb_book.series_id
     *
     * @mbggenerated
     */
    public Integer getSeriesId() {
        return seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.series_id
     *
     * @param seriesId the value for tb_book.series_id
     *
     * @mbggenerated
     */
    public void setSeriesId(Integer seriesId) {
        this.seriesId = seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.exchange_type
     *
     * @return the value of tb_book.exchange_type
     *
     * @mbggenerated
     */
    public String getExchangeType() {
        return exchangeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.exchange_type
     *
     * @param exchangeType the value for tb_book.exchange_type
     *
     * @mbggenerated
     */
    public void setExchangeType(String exchangeType) {
        this.exchangeType = exchangeType == null ? null : exchangeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.limit_price
     *
     * @return the value of tb_book.limit_price
     *
     * @mbggenerated
     */
    public Integer getLimitPrice() {
        return limitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.limit_price
     *
     * @param limitPrice the value for tb_book.limit_price
     *
     * @mbggenerated
     */
    public void setLimitPrice(Integer limitPrice) {
        this.limitPrice = limitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.limit_start_time
     *
     * @return the value of tb_book.limit_start_time
     *
     * @mbggenerated
     */
    public Integer getLimitStartTime() {
        return limitStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.limit_start_time
     *
     * @param limitStartTime the value for tb_book.limit_start_time
     *
     * @mbggenerated
     */
    public void setLimitStartTime(Integer limitStartTime) {
        this.limitStartTime = limitStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.limit_end_time
     *
     * @return the value of tb_book.limit_end_time
     *
     * @mbggenerated
     */
    public Integer getLimitEndTime() {
        return limitEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.limit_end_time
     *
     * @param limitEndTime the value for tb_book.limit_end_time
     *
     * @mbggenerated
     */
    public void setLimitEndTime(Integer limitEndTime) {
        this.limitEndTime = limitEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.update_time
     *
     * @return the value of tb_book.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.update_time
     *
     * @param updateTime the value for tb_book.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}