package com.kingsoft.pojo;

public class YellowCrawlerError {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yellow_crawler_error.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yellow_crawler_error.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yellow_crawler_error.publish_date
     *
     * @mbggenerated
     */
    private String publishDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yellow_crawler_error.id
     *
     * @return the value of tb_yellow_crawler_error.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yellow_crawler_error.id
     *
     * @param id the value for tb_yellow_crawler_error.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yellow_crawler_error.url
     *
     * @return the value of tb_yellow_crawler_error.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yellow_crawler_error.url
     *
     * @param url the value for tb_yellow_crawler_error.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yellow_crawler_error.publish_date
     *
     * @return the value of tb_yellow_crawler_error.publish_date
     *
     * @mbggenerated
     */
    public String getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yellow_crawler_error.publish_date
     *
     * @param publishDate the value for tb_yellow_crawler_error.publish_date
     *
     * @mbggenerated
     */
    public void setPublishDate(String publishDate) {
        this.publishDate = publishDate == null ? null : publishDate.trim();
    }
}