package com.kingsoft.pojo;

import java.util.Date;

public class YellowBookSection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yellow_book_section.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yellow_book_section.section_title
     *
     * @mbggenerated
     */
    private String sectionTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yellow_book_section.section_url
     *
     * @mbggenerated
     */
    private String sectionUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yellow_book_section.words
     *
     * @mbggenerated
     */
    private Integer words;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yellow_book_section.label
     *
     * @mbggenerated
     */
    private Integer label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yellow_book_section.publish_date
     *
     * @mbggenerated
     */
    private String publishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yellow_book_section.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yellow_book_section.section_content
     *
     * @mbggenerated
     */
    private String sectionContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yellow_book_section.id
     *
     * @return the value of tb_yellow_book_section.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yellow_book_section.id
     *
     * @param id the value for tb_yellow_book_section.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yellow_book_section.section_title
     *
     * @return the value of tb_yellow_book_section.section_title
     *
     * @mbggenerated
     */
    public String getSectionTitle() {
        return sectionTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yellow_book_section.section_title
     *
     * @param sectionTitle the value for tb_yellow_book_section.section_title
     *
     * @mbggenerated
     */
    public void setSectionTitle(String sectionTitle) {
        this.sectionTitle = sectionTitle == null ? null : sectionTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yellow_book_section.section_url
     *
     * @return the value of tb_yellow_book_section.section_url
     *
     * @mbggenerated
     */
    public String getSectionUrl() {
        return sectionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yellow_book_section.section_url
     *
     * @param sectionUrl the value for tb_yellow_book_section.section_url
     *
     * @mbggenerated
     */
    public void setSectionUrl(String sectionUrl) {
        this.sectionUrl = sectionUrl == null ? null : sectionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yellow_book_section.words
     *
     * @return the value of tb_yellow_book_section.words
     *
     * @mbggenerated
     */
    public Integer getWords() {
        return words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yellow_book_section.words
     *
     * @param words the value for tb_yellow_book_section.words
     *
     * @mbggenerated
     */
    public void setWords(Integer words) {
        this.words = words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yellow_book_section.label
     *
     * @return the value of tb_yellow_book_section.label
     *
     * @mbggenerated
     */
    public Integer getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yellow_book_section.label
     *
     * @param label the value for tb_yellow_book_section.label
     *
     * @mbggenerated
     */
    public void setLabel(Integer label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yellow_book_section.publish_date
     *
     * @return the value of tb_yellow_book_section.publish_date
     *
     * @mbggenerated
     */
    public String getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yellow_book_section.publish_date
     *
     * @param publishDate the value for tb_yellow_book_section.publish_date
     *
     * @mbggenerated
     */
    public void setPublishDate(String publishDate) {
        this.publishDate = publishDate == null ? null : publishDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yellow_book_section.update_time
     *
     * @return the value of tb_yellow_book_section.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yellow_book_section.update_time
     *
     * @param updateTime the value for tb_yellow_book_section.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yellow_book_section.section_content
     *
     * @return the value of tb_yellow_book_section.section_content
     *
     * @mbggenerated
     */
    public String getSectionContent() {
        return sectionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yellow_book_section.section_content
     *
     * @param sectionContent the value for tb_yellow_book_section.section_content
     *
     * @mbggenerated
     */
    public void setSectionContent(String sectionContent) {
        this.sectionContent = sectionContent == null ? null : sectionContent.trim();
    }
}