package com.kingsoft.pojo;

import java.util.Date;

public class YellowBookLabel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yellow_book_label.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yellow_book_label.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yellow_book_label.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yellow_book_label.id
     *
     * @return the value of tb_yellow_book_label.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yellow_book_label.id
     *
     * @param id the value for tb_yellow_book_label.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yellow_book_label.type
     *
     * @return the value of tb_yellow_book_label.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yellow_book_label.type
     *
     * @param type the value for tb_yellow_book_label.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yellow_book_label.update_time
     *
     * @return the value of tb_yellow_book_label.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yellow_book_label.update_time
     *
     * @param updateTime the value for tb_yellow_book_label.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}